version: "4.28"

services:
  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    ports:
      - 8081:8081
    networks:
      - project_network

  frontend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend:/app/backend

networks:
  project_network: